module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "Color-Brand-Brand-Purple-500": "#B531FDFF",
        "Color-Brand-Brand-Purple-300": "#D07AFEFF",
        "Color-Brand-Brand-Blud-500": "#00B4FEFF",
        "Color-Brand-Brand-Blud-300": "#6CD4FFFF",
        "Color-State-Safe": "#3DD08CFF",
        "Color-State-Warn": "#FFA600FF",
        "Color-State-Danger": "#FF5959FF",
        "Color-State-Link": "#8016BFFF",
        "Color-State-Link--hover": "#D07AFEFF",
        "Color-Grey-Grey-900": "#2F2F3EFF",
        "Color-Grey-Grey-600": "#5D5D7BFF",
        "Color-Grey-Grey-500": "#8181A0FF",
        "Color-Grey-Grey-300": "#AAAABFFF",
        "Color-Grey-Grey-100": "#DBDBEBFF",
        "Color-Grey-Grey-50": "#F5F5F7FF",
        "Color-Grey-Grey-000": "#FFFFFFFF",
      },
      spacing: {
        "Spacing-1": "8px",
        "Spacing-2": "16px",
        "Spacing-3": "24px",
        "Spacing-4": "32px",
        "Spacing-5": "40px",
        "Spacing-6": "56px",
        "Spacing-7": "72px",
        "Spacing-8": "80px",
        "Spacing-9": "96px",
        "Spacing-10": "120px",
        "Radius-1": "5px",
        "Radius-2": "10px",
        "Radius-3": "15px",
        "Radius-4": "20px",
        "Radius-5": "500px",
      },
    },
  },
  plugins: [],
};
