export enum TabBarItem {
  BASIC_INFO = 'BASIC_INFO',
  MARKET_INFO = 'MARKET_INFO',
  OPERATIONS = 'OPERATIONS',
  FINANCIAL_REPORT = 'FINANCIAL_REPORT',
  FLAGS = 'FLAGS',
  DISCUSSION = 'DISCUSSION',
}

export const TAB_BAR_ITEMS: TabBarItem[] = Object.values(TabBarItem);
