import type { Metadata } from 'next';
import { Noto_Sans_TC, Jost } from 'next/font/google';
import '@/styles/globals.css';

const notoSansTC = Noto_Sans_TC({
  subsets: ['latin'],
});

const jost = Jost({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansTC.className} ${jost.className} antialiased`}>{children}</body>
    </html>
  );
}
