name: Build OpenAPI & Types

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Generate OpenAPI
        run: npm run gen:openapi

      - name: Generate Types (.d.ts)
        run: npm run gen:types

      - name: Upload OpenAPI
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: openapi.json
          if-no-files-found: error

      - name: Upload Types
        uses: actions/upload-artifact@v4
        with:
          name: types
          path: types/**
          if-no-files-found: error
