name: Unit & Integration Tests

on:
  push:
    branches:
      - feature/*
      - fix/*
      - hotfix/*
  pull_request:
    branches:
      - develop
      - main

jobs:
  backend-integration-tests:
    runs-on: ubuntu-latest
    container: node:20-slim
    services:
      postgres:
        image: postgres:16
        env: { POSTGRES_PASSWORD: postgres }
        options: >-
          --health-cmd pg_isready --health-interval 10s
          --health-timeout 5s --health-retries 5
        ports: [ "5432:5432" ]

    steps:
      - uses: actions/checkout@v4
      - run: npm ci

      - name: Choose DB (prefer real)
        id: setdb
        run: |
          if [ -n "${{ secrets.IT_DATABASE_URL }}" ]; then
            echo "DATABASE_URL=${{ secrets.IT_DATABASE_URL }}" >> $GITHUB_ENV
            echo "mode=real" >> $GITHUB_OUTPUT
          else
            echo "DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres" >> $GITHUB_ENV
            echo "mode=container" >> $GITHUB_OUTPUT
          fi

      - name: Migrate & seed (container only)
        if: steps.setdb.outputs.mode == 'container'
        run: |
          npx prisma migrate deploy
          npx prisma db seed

      - name: Run integration tests
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          NEXT_PUBLIC_API_POWERBY: "BusinessMonitor api 1.0.0-ci"
        run: npm run test:it
